name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit flake8 pytest pip-audit

      - name: Run Bandit (Static Analysis)
        run: |
          bandit -r . -f txt -o bandit_report.txt || true

      - name: Run pip-audit (Dependency Scan)
        run: |
          python -m pip_audit > dependency_audit.txt || true

      - name: Run Flake8 (Code Quality)
        run: |
          flake8 . --statistics --exclude=venv,__pycache__,.git,*.pyc > flake8_report.txt || true

      - name: Run Pytest (Functional Tests)
        run: |
          pytest pytest_security.py -v > pytest_report.txt || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: Security-Reports
          path: |
            bandit_report.txt
            dependency_audit.txt
            flake8_report.txt
            pytest_report.txt
